/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.senai.sp.jandira.ui;

/**
 *
 * @author 22282080
 */
public class MedicoDialog extends javax.swing.JDialog {

    /**
     * Creates new form MedicoDialog
     */
    public MedicoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tipoDoPlano = new javax.swing.JLabel();
        labelCodigo = new javax.swing.JLabel();
        nomeDoPlano = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textTipoDoPlano = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        textFieldCodigo = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        textNomeDaOperadora = new javax.swing.JTextPane();
        buttonCancelar = new javax.swing.JButton();
        buttonSalvar = new javax.swing.JButton();
        detalhesPlanoDeSaude = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        iconTitulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelTitulo1 = new javax.swing.JLabel();
        iconTitulo1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        detalhesMedico = new javax.swing.JLabel();
        labelCodigo2 = new javax.swing.JLabel();
        crm = new javax.swing.JLabel();
        nomeDoMedico = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelDataDeNascimento = new javax.swing.JLabel();
        labelListaDeEspecialidades = new javax.swing.JLabel();
        labelEspecialidadesDosMedicos = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textTelefone = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        textFieldCodigo1 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        textEmail = new javax.swing.JTextPane();
        buttonCancelar1 = new javax.swing.JButton();
        buttonSalvar1 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        textDataDeNascimento = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        textNomeDoMedico = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        textCrm = new javax.swing.JTextPane();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        tipoDoPlano.setText("Tipo do plano:");
        jPanel2.add(tipoDoPlano);
        tipoDoPlano.setBounds(20, 160, 80, 16);

        labelCodigo.setText("Código:");
        jPanel2.add(labelCodigo);
        labelCodigo.setBounds(20, 50, 50, 16);

        nomeDoPlano.setText("Nome:");
        jPanel2.add(nomeDoPlano);
        nomeDoPlano.setBounds(20, 100, 50, 16);

        jScrollPane1.setViewportView(textTipoDoPlano);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 180, 260, 22);

        textFieldCodigo.setEditable(false);
        jScrollPane2.setViewportView(textFieldCodigo);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 70, 80, 22);

        jScrollPane3.setViewportView(textNomeDaOperadora);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(20, 120, 260, 22);

        buttonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/delete.png"))); // NOI18N
        buttonCancelar.setToolTipText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(buttonCancelar);
        buttonCancelar.setBounds(450, 230, 70, 60);

        buttonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/save32.png"))); // NOI18N
        buttonSalvar.setToolTipText("Salvar novo plano");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSalvar);
        buttonSalvar.setBounds(540, 230, 70, 60);

        detalhesPlanoDeSaude.setText("Detalhes do Plano de Saúde ");
        jPanel2.add(detalhesPlanoDeSaude);
        detalhesPlanoDeSaude.setBounds(20, 10, 150, 16);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        labelTitulo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Plano de Saúde - Adicionar");
        jPanel1.add(labelTitulo);
        labelTitulo.setBounds(90, 20, 500, 40);

        iconTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/addPlano64.png"))); // NOI18N
        jPanel1.add(iconTitulo);
        iconTitulo.setBounds(10, 10, 70, 70);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(671, 504));
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(null);

        labelTitulo1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        labelTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo1.setText("Médico - Adicionar");
        jPanel4.add(labelTitulo1);
        labelTitulo1.setBounds(90, 20, 500, 40);

        iconTitulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/addPlano64.png"))); // NOI18N
        jPanel4.add(iconTitulo1);
        iconTitulo1.setBounds(10, 10, 70, 70);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 670, 80);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        detalhesMedico.setText("Detalhes do Médico:");
        jPanel3.add(detalhesMedico);
        detalhesMedico.setBounds(20, 10, 150, 16);

        labelCodigo2.setText("Código:");
        jPanel3.add(labelCodigo2);
        labelCodigo2.setBounds(20, 50, 50, 16);

        crm.setText("CRM:");
        jPanel3.add(crm);
        crm.setBounds(110, 50, 80, 16);

        nomeDoMedico.setText("Nome do(a) Médico(a):");
        jPanel3.add(nomeDoMedico);
        nomeDoMedico.setBounds(240, 50, 140, 16);

        labelTelefone.setText("Telefone:");
        jPanel3.add(labelTelefone);
        labelTelefone.setBounds(20, 110, 50, 16);

        labelEmail.setText("E-mail:");
        jPanel3.add(labelEmail);
        labelEmail.setBounds(160, 110, 50, 16);

        labelDataDeNascimento.setText("Data de Nascimento:");
        jPanel3.add(labelDataDeNascimento);
        labelDataDeNascimento.setBounds(490, 110, 120, 16);

        labelListaDeEspecialidades.setText("Lista de especialidades:");
        jPanel3.add(labelListaDeEspecialidades);
        labelListaDeEspecialidades.setBounds(20, 170, 130, 16);

        labelEspecialidadesDosMedicos.setText("Especialidades dos médicos:");
        jPanel3.add(labelEspecialidadesDosMedicos);
        labelEspecialidadesDosMedicos.setBounds(240, 170, 160, 16);

        jScrollPane4.setViewportView(textTelefone);

        jPanel3.add(jScrollPane4);
        jScrollPane4.setBounds(20, 130, 130, 22);

        textFieldCodigo1.setEditable(false);
        jScrollPane5.setViewportView(textFieldCodigo1);

        jPanel3.add(jScrollPane5);
        jScrollPane5.setBounds(20, 70, 80, 22);

        jScrollPane6.setViewportView(textEmail);

        jPanel3.add(jScrollPane6);
        jScrollPane6.setBounds(160, 130, 320, 22);

        buttonCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/delete.png"))); // NOI18N
        buttonCancelar1.setToolTipText("Cancelar");
        buttonCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelar1ActionPerformed(evt);
            }
        });
        jPanel3.add(buttonCancelar1);
        buttonCancelar1.setBounds(450, 290, 70, 60);

        buttonSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/save32.png"))); // NOI18N
        buttonSalvar1.setToolTipText("Salvar novo plano");
        buttonSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvar1ActionPerformed(evt);
            }
        });
        jPanel3.add(buttonSalvar1);
        buttonSalvar1.setBounds(540, 290, 70, 60);
        buttonSalvar1.getAccessibleContext().setAccessibleDescription("Salvar");

        jScrollPane7.setViewportView(textDataDeNascimento);

        jPanel3.add(jScrollPane7);
        jScrollPane7.setBounds(490, 130, 120, 22);

        jScrollPane8.setViewportView(textNomeDoMedico);

        jPanel3.add(jScrollPane8);
        jScrollPane8.setBounds(240, 70, 370, 22);

        jScrollPane9.setViewportView(textCrm);

        jPanel3.add(jScrollPane9);
        jScrollPane9.setBounds(110, 70, 120, 22);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 110, 630, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed

        dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
      
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void buttonCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelar1ActionPerformed

        dispose();
    }//GEN-LAST:event_buttonCancelar1ActionPerformed

    private void buttonSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvar1ActionPerformed
      
    }//GEN-LAST:event_buttonSalvar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MedicoDialog dialog = new MedicoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonCancelar1;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JButton buttonSalvar1;
    private javax.swing.JLabel crm;
    private javax.swing.JLabel detalhesMedico;
    private javax.swing.JLabel detalhesPlanoDeSaude;
    private javax.swing.JLabel iconTitulo;
    private javax.swing.JLabel iconTitulo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelCodigo2;
    private javax.swing.JLabel labelDataDeNascimento;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEspecialidadesDosMedicos;
    private javax.swing.JLabel labelListaDeEspecialidades;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JLabel nomeDoMedico;
    private javax.swing.JLabel nomeDoPlano;
    private javax.swing.JTextPane textCrm;
    private javax.swing.JTextPane textDataDeNascimento;
    private javax.swing.JTextPane textEmail;
    private javax.swing.JTextPane textFieldCodigo;
    private javax.swing.JTextPane textFieldCodigo1;
    private javax.swing.JTextPane textNomeDaOperadora;
    private javax.swing.JTextPane textNomeDoMedico;
    private javax.swing.JTextPane textTelefone;
    private javax.swing.JTextPane textTipoDoPlano;
    private javax.swing.JLabel tipoDoPlano;
    // End of variables declaration//GEN-END:variables
}
